export const FETCH_BOARD_REQUEST = 'FETCH_BOARD_REQUEST';
export const FETCH_BOARD_SUCCESS = 'FETCH_BOARD_SUCCESS';
export const FETCH_BOARD_FAILURE = 'FETCH_BOARD_FAILURE';

export const ADD_COLUMN = 'ADD_COLUMN';
export const UPDATE_COLUMN = 'UPDATE_COLUMN';
export const DELETE_COLUMN = 'DELETE_COLUMN';
export const MOVE_COLUMN = 'MOVE_COLUMN';
export const ADD_COLUMN_SUCCESS = 'ADD_COLUMN_SUCCESS';
export const DELETE_COLUMN_SUCCESS = 'DELETE_COLUMN_SUCCESS';


export const ADD_TASK = 'ADD_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const MOVE_TASK = 'MOVE_TASK'; 


export const FETCH_USER_BOARDS_REQUEST = 'FETCH_USER_BOARDS_REQUEST';
export const FETCH_USER_BOARDS_SUCCESS = 'FETCH_USER_BOARDS_SUCCESS';
export const FETCH_USER_BOARDS_FAILURE = 'FETCH_USER_BOARDS_FAILURE';

export const CREATE_USER_BOARD = 'CREATE_USER_BOARD';
export const DELETE_USER_BOARD = 'DELETE_USER_BOARD';

